version: '3.8'
services:
  web:
    build: .
    command: /run.bash
    volumes:
      - .:/app
    ports:
      - 8000:8000
    depends_on:
      - db
    env_file:
      - ./.env.dev
  db:
    image: postgres
    environment:
      - POSTGRES_DB=fincsidb
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres

    volumes:
      - postgres_data:/var/lib/postgresql/data/
volumes:
  postgres_data:
