# Generated by Django 4.2.7 on 2023-11-27 01:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('falatok', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='guides',
            field=models.URLField(blank=True, null=True),
        ),
    ]
